use anyhow::{anyhow, bail, Context, Result};
use clap::{Parser, Subcommand};
use std::path::{Path, PathBuf};
use std::process::Command;

/// C to Rust migration with verification report. Verifier-first.
#[derive(Parser)]
#[command(name = "c2proof", version)]
pub struct Cli {
    #[command(subcommand)]
    cmd: Cmd,
}

#[derive(Subcommand)]
pub enum Cmd {
    /// Migrate a flat C repo into a compiling Rust port PR + verification report.
    Migrate {
        repo_url: String,
        /// Run against the committed golden fixture instead of real c2rust.
        #[arg(long)]
        fixture: bool,
    },
}

pub const RUNNER_IMAGE: &str = "ghcr.io/akashpriyadarshii/c2proof/runner:c2rust-0.20.0";

impl Cli {
    pub fn run(self) -> i32 {
        match self.cmd {
            Cmd::Migrate { repo_url, fixture } => migrate(&repo_url, fixture),
        }
    }
}

pub fn migrate(repo_url: &str, use_fixture: bool) -> i32 {
    match run(repo_url, use_fixture) {
        Ok(()) => 0,
        Err(e) => {
            eprintln!("error: {e:#}");
            if format!("{e:#}").starts_with("refused:") {
                2
            } else {
                1
            }
        }
    }
}

pub fn run(repo_url: &str, use_fixture: bool) -> Result<()> {
    let tmp = tempfile_dir()?;
    let src = prepare_source(repo_url, &tmp)?;
    scan_gate(&src)?;

    let out = tmp.join("out-crate");
    if use_fixture {
        transpile_fixture(&out)?;
    } else {
        transpile_c2rust(&src, &out)?;
    }

    cargo(&["check"], &out).context("cargo check on transpiled crate")?;
    println!("pipeline ok; PR push lands in T08");
    Ok(())
}

// ponytail: tempdir via std env TMP, manual cleanup skipped — short-lived dirs fine for v0.1.
fn tempfile_dir() -> Result<PathBuf> {
    let d = std::env::temp_dir().join(format!("c2proof-{}-{}", std::process::id(), fastrand_id()));
    std::fs::create_dir_all(&d)?;
    Ok(d)
}

fn fastrand_id() -> u128 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0)
}

fn prepare_source(repo_url: &str, tmp: &Path) -> Result<PathBuf> {
    if Path::new(repo_url).is_dir() {
        return Ok(PathBuf::from(repo_url));
    }
    let dest = tmp.join("src-repo");
    git(&["clone", "--depth", "1", repo_url, dest.to_str().unwrap()])
        .context("git clone (is the URL reachable?)")?;
    Ok(dest)
}

fn git(args: &[&str]) -> Result<()> {
    let out = Command::new("git").args(args).output()?;
    ensure_success("git", out)
}

fn cargo(args: &[&str], cwd: &Path) -> Result<()> {
    let out = Command::new("cargo")
        .args(args)
        .current_dir(cwd)
        .env_remove("CARGO_MANIFEST_DIR") // isolate from c2proof's own build
        .output()?;
    ensure_success("cargo", out)
}

fn ensure_success(cmd: &str, out: std::process::Output) -> Result<()> {
    if out.status.success() {
        return Ok(());
    }
    let tail = String::from_utf8_lossy(&out.stderr);
    let tail = tail.lines().rev().take(10).collect::<Vec<_>>().join("\n");
    bail!("{cmd} failed:\n{tail}")
}

/// Refuse anything that is not a flat .c/.h directory. Exit code 2.
pub fn scan_gate(dir: &Path) -> Result<()> {
    let mut c_files = 0usize;
    for entry in std::fs::read_dir(dir)? {
        let entry = entry?;
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if entry.file_type()?.is_dir() {
            if name == ".git" || name == "target" {
                continue;
            }
            bail!("refused: subdirectory '{name}' present — v0.1.0 supports flat C projects only");
        }
        if !(name.ends_with(".c")
            || name.ends_with(".h")
            || name == "LICENSE"
            || name == "README.md"
            || name.starts_with('.'))
        {
            bail!("refused: unexpected file '{name}' — expected only .c/.h");
        }
        if name.ends_with(".c") || name.ends_with(".h") {
            c_files += 1;
        }
    }
    if c_files == 0 {
        bail!("refused: no .c/.h files found");
    }
    Ok(())
}

fn fixture_root() -> PathBuf {
    // Test/CI override; defaults to the golden fixture regenerated by the e2e job.
    std::env::var_os("C2PROOF_FIXTURE_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../tests/fixtures/tinyexpr")
        })
}

fn transpile_fixture(out: &Path) -> Result<()> {
    let fixture = fixture_root();
    copy_dir(&fixture, out)
        .map_err(|e| anyhow!("fixture missing or unreadable ({e}) — regenerate via CI e2e job"))
}

fn transpile_c2rust(src: &Path, out: &Path) -> Result<()> {
    let docker = Command::new("docker").arg("--version").output();
    match docker {
        Err(_) => bail!(
            "docker not found — install Docker Desktop, or rerun with --fixture to test offline"
        ),
        Ok(o) if !o.status.success() => {
            bail!("docker not usable — install Docker Desktop, or rerun with --fixture")
        }
        _ => {}
    }
    std::fs::create_dir_all(out)?;
    let status = Command::new("docker")
        .args([
            "run",
            "--rm",
            "-v",
            &format!("{}:/work/src", src.canonicalize()?.display()),
            "-v",
            &format!("{}:/work/out", out.canonicalize()?.display()),
            RUNNER_IMAGE,
            "transpile",
            "--emit-build-files",
            "/work/src",
        ])
        .status()?;
    if !status.success() {
        bail!("c2rust container failed");
    }
    Ok(())
}

fn copy_dir(src: &Path, dst: &Path) -> std::io::Result<()> {
    std::fs::create_dir_all(dst)?;
    for entry in std::fs::read_dir(src)? {
        let entry = entry?;
        let ty = entry.file_type()?;
        let target = dst.join(entry.file_name());
        if ty.is_dir() {
            copy_dir(&entry.path(), &target)?;
        } else {
            std::fs::copy(entry.path(), target)?;
        }
    }
    Ok(())
}
